#!/usr/bin/env python3
"""
Extract Facebook cookies from your browser for yt-dlp

This script helps you extract Facebook cookies so the bot can download private videos.

Requirements:
    pip install browser-cookie3

Usage:
    python get_facebook_cookies.py

The script will:
1. Log you into Facebook in your browser
2. Extract the cookies
3. Save them to a file (facebook_cookies.txt)
4. Update your .env file with the cookie path
"""

import os
import sys

try:
    import browser_cookie3
except ImportError:
    print("❌ browser-cookie3 not installed!")
    print("Install it with: pip install browser-cookie3")
    sys.exit(1)


def get_facebook_cookies():
    """Extract Facebook cookies from browser."""
    print("🍪 Extracting Facebook cookies...")
    print()
    print("⚠️  IMPORTANT: You must be logged into Facebook in your browser first!")
    print()
    
    # Try different browsers
    browsers = [
        ('Chrome', browser_cookie3.chrome),
        ('Chromium', browser_cookie3.chromium),
        ('Firefox', browser_cookie3.firefox),
        ('Edge', browser_cookie3.edge),
    ]
    
    cookies = None
    browser_name = None
    
    for name, browser_func in browsers:
        try:
            print(f"Trying {name}...")
            cookies = browser_func(domain_name='facebook.com')
            if cookies:
                browser_name = name
                print(f"✅ Found Facebook cookies in {name}!")
                break
        except Exception as e:
            print(f"   {name}: Not found or error ({e})")
    
    if not cookies:
        print("\n❌ Could not find Facebook cookies in any browser!")
        print("\n💡 Solution:")
        print("   1. Open your browser")
        print("   2. Go to https://www.facebook.com and log in")
        print("   3. Run this script again")
        return None
    
    # Save cookies to file
    cookie_file = "facebook_cookies.txt"
    
    # Export cookies in Netscape format
    with open(cookie_file, 'w') as f:
        f.write("# Netscape HTTP Cookie File\n")
        f.write("# This file was generated by get_facebook_cookies.py\n\n")
        
        for cookie in cookies:
            if cookie.domain and cookie.name and cookie.value:
                domain = cookie.domain
                if not domain.startswith('.'):
                    domain = '.' + domain
                f.write(f"{domain}\t")
                f.write(f"{'TRUE' if cookie.domain_specified else 'FALSE'}\t")
                f.write(f"{cookie.path}\t")
                f.write(f"{'TRUE' if cookie.secure else 'FALSE'}\t")
                f.write(f"{int(cookie.expires) if cookie.expires else 0}\t")
                f.write(f"{cookie.name}\t")
                f.write(f"{cookie.value}\n")
    
    print(f"\n✅ Cookies saved to: {os.path.abspath(cookie_file)}")
    
    # Update .env file
    env_file = ".env"
    if os.path.exists(env_file):
        with open(env_file, 'r') as f:
            content = f.read()
        
        # Update FACEBOOK_COOKIES line
        if 'FACEBOOK_COOKIES=' in content:
            content = content.replace(
                'FACEBOOK_COOKIES=',
                f'FACEBOOK_COOKIES={os.path.abspath(cookie_file)}'
            )
        else:
            content += f'\nFACEBOOK_COOKIES={os.path.abspath(cookie_file)}\n'
        
        with open(env_file, 'w') as f:
            f.write(content)
        
        print(f"✅ Updated {env_file} with cookie path")
    else:
        print(f"\n⚠️  .env file not found!")
        print(f"   Add this line to your .env file manually:")
        print(f"   FACEBOOK_COOKIES={os.path.abspath(cookie_file)}")
    
    print("\n" + "="*50)
    print("✅ DONE!")
    print("\nNext steps:")
    print("1. Restart your bot: python bot.py")
    print("2. Try downloading the Facebook video again")
    print("\n⚠️  Note: Cookies expire! Re-run this script if downloads stop working.")
    print("="*50)
    
    return cookie_file


if __name__ == "__main__":
    get_facebook_cookies()
